config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :blogs
  get 'pages/home'
  get 'pages/about'
  devise_for :users, path: '', path_names: {sing_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
  	member do
  		get :toggle_status
  	end
  end
  
  root to: 'pages#home'#setting index as homepage
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/forward.rb
class Forward < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/guest_user.rb
class GuestUser < User
	attr_accessor :name, :first_name, :last_name, :email
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :forwards, :dependent => :destroy
    has_many :users, through: :forwards   

    accepts_nested_attributes_for :forwards, reject_if: lambda { |attrs| attrs['user_id'].blank? }
   # accepts_nested_attributes_for :users, reject_if: lambda { |attrs| attrs['user_id'].blank?}
	enum status: {draft: 0, published: 1}
    extend FriendlyId
    friendly_id :title, use: :slugged
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_many :forwards, :dependent => :destroy
  has_many :posts, through: :forwards    
  accepts_nested_attributes_for :posts
  accepts_nested_attributes_for :forwards

  
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_ad min can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name

  def first_name
     self.name.split.first
  end

  def last_name
     self.name.split.last
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include DeviseWhitelist
	include CurrentUserConcern
	include PageContent

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  # GET /blogs
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /blogs/1
  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
	extend ActiveSupport::Concern
	 def current_user
	 	super || guest_user
    end
    def guest_user
    	guest = GuestUser.new
    	guest.name = "Guest User"
    	guest.first_name = "Guest"
    	guest.last_name = "User"
    	guest.email = "abc@xyz.com"
        guest
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
    extend ActiveSupport::Concern

    included do |variable|
 		before_action  :configure_permitted_parameters, if: :devise_controller?

    end
    def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end 
end   

app/controllers/concerns/page_content.rb
module PageContent
  extend ActiveSupport::Concern

    included do 
       before_action :set_title
    end

    def set_title 
      @page_title = "Post Manager"
   end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy toggle_status]
  access all: [:show, :index], user: :all, site_admin: :all
  layout "post"
  # GET /posts or /posts.json
  def index
    @posts = Post.published
    @page_title = "Posts"
  end

  # GET /posts/1 or /posts/1.json
  def show
    @page_title = @post.title
  end

  # GET /posts/new
  def new
    @post = Post.new
    3.times { @post.forwards.build }
  
  end


  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    #@post = Post.new(params.require(:post).permit(:title, :body, users_attributes: [:user_id]))
    #@post = Post.new(params.require(:post).permit(:title, :body)
    @post = Post.new(post_params)
    respond_with Post.create(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @post.draft?
      @post.published!
    elsif @post.published?
      @post.draft!
    end
    redirect_to posts_url
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, forwards_attributes: [:user_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /users

  def index    
    if current_user
     # @users = User.includes(:posts).all
     @user = current_user

    else
      redirect_to new_user_session_path, notice: 'You are not logged in.'
    end
  end

  # GET /users/1
  def show

  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end



    # Only allow a trusted parameter "white list" through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

      }
    </style>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>   
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
        <div>
           <%= render "shared/application_nav"%>
           <%= yield %>
        </div>
      </header>
    </div>

  </body>
</html>

app/views/layouts/post.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto+Slab" rel="stylesheet">

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/blog_nav' %>
    <%= render 'shared/blog_masthead' %>

    <div class="container">

      <div class="row">

        <%= yield %>

        <%= render 'shared/blog_sidebar' %>
      </div>

      <%= render 'shared/blog_footer' %>

      <%= alerts %>
    </div>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto+Slab" rel="stylesheet">

    <meta name="keywords" content="<%= @seo_keywords %>" />



    <%= stylesheet_link_tag    'users', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <div class="container">

      <div class="row">

        <%= yield %>

      </div>

    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Homepage</h3>

      </nav>
    </div>
  </header>
</div>
<main class="px-3">
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Express your views <a 
    class="text-white">Post manager</a>, by <a class="text-white">@mdo</a>.</p>
  </footer>
</div>

app/views/posts/_form.html.erb
 <%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :Image %>
    <%= form.text_area :Image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="blog-post blog-body">
  <h2 class="blog-post-title"><%= link_to post.title, post %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(post.created_at, Time.now) %> ago</p>
  
  <%= render partial: 'posts/admin_actions', locals: { post: post } %>

  <p>
    <%= truncate(markdown(post.body), length: 600, escape: false) %>
    <%= link_to "Continue reading", post %>
  </p>
</div>

app/views/posts/edit.html.erb
<h2></h2>
<div class="card" style="width: 25rem;">
  <div class="card-body">
    <h5 class="card-title"> New Post </h5>
      <% if post.errors.any? %>
         <div id="error_explanation">
           <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

           <ul>
             <% post.errors.each do |error| %>
               <li><%= error.full_message %></li>
             <% end %>
          </ul>
         </div>
       <% end %>
      <%= form_for(@post) do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
     <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= form.label :main_image %>
        <%= form.text_area :main_image, class: 'form-control' %>
      </div>
    
      <div class="actions">
        <%= form.submit "Edit", class: 'btn btn-primary' %>
      </div>
    <% end %>


  </div>
</div>


<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/home.html.erb
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Cover</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">Contact</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    <h1>Cover your page.</h1>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<html lang="en">
<table>
  <thead>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

      <th colspan="4"></th>
    </tr>
  </thead>
  <%= render "shared/application_nav"%>
  <h1>Posts</h1>

<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="blog-header-logo text-dark" href="#">Title</a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="#">Body</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="#" aria-label="Search">
        <title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a>
      </div>
    </div>
  </header>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
    <% end %>
  </tbody>
</table>
 

<br>
</html>


<%= link_to 'New Post', new_post_path if logged_in?(:site_admin) %>

app/views/posts/new.html.erb
<h2></h2>
<div class="card" style="width: 50rem;">
  <div class="card-body">
    <h5 class="card-title"> New Post </h5>

      <%= form_for(@post) do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
     <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control' %>
      </div>
    
      <ul>
        <%= form.fields_for :forwards do |forward_form| %>
          <li>
            <%= forward_form.label :user_id, "Share with" %>
            <%= forward_form.number_field :user_id, class: 'form-control' %>
          </li>
        <% end %>
      </ul>
    
      <div class="actions">
        <%= form.submit "create", class: 'btn btn-primary' %>
      </div>
    <% end %>


  </div>
</div>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @post.id %></h1>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<strong> Shared with:</strong>

<% @post.forwards.each do |t| %>
<p><%= t.user_id %></p>
<% end %>


<%= link_to 'Back', posts_path %>

app/views/shared/_application_nav.html.erb
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <%= link_to "Home", root_path, class: 'nav-link' %>
        <%= link_to "About", pages_about_path, class: 'nav-link' %>
        <%= link_to "Posts", posts_path, class: 'nav-link' %>
        <% if current_user.is_a?(GuestUser)%>
          <%= link_to "Register", new_user_registration_path, class: 'nav-link' %>
          <%= link_to "Login", new_user_session_path, class: 'nav-link'%>

       <% else %>
         <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
         <%= link_to "Your Posts", users_url, class: 'nav-link'%>

       <% end %>  
    </div>
  </header>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
 <div><%= link_to "Home", root_path %></div>
 <div><%= link_to "About", pages_about_path %></div>
 <div><%= link_to "Posts", posts_path %></div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<html lang="en">
<table>
  <thead>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

      <th colspan="4"></th>
    </tr>
  </thead>
  <h1>Posts</h1>

<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="blog-header-logo text-dark" href="#">Title</a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="#">Body</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="#" aria-label="Search">
        <title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a>
      </div>
    </div>
  </header>

  <tbody>
    <div class="user">
        <% @user.posts.each do |p| %>
            <div class="col-4 pt-1">
            <a class="blog-header-logo text-dark" href="#">
            <td><%= p.title %></td>                
            </a>
            </div>
            <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="#">
            <td><%= p.body %></td>
            </a>
            <td><%= link_to p.status, toggle_status_post_path(p)%></td>
            <td><%= link_to 'Show', p %></td>
            <td><%= link_to 'Destroy', p, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%></td>
          </tr>  
        <% end %>     
  </tbody>
</table>
 

<br>
</html>


<%= link_to 'New Post', new_post_path if logged_in?(:site_admin) %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>